### ISSUE TITLE
OSC on timeline ?

### ISSUE THREAD

**Issue by stephanebordonaro** [maybites/blender.NodeOSC#10]
hello,
i don't know if it's the right place for this.
is there a way to control by OSC the curseur on the timeline to point to a spectific time   or the disable/enable an objet on scene ? 
thx for your reply

**Comment by maybites** [comment]
yes, thats totally possible:

time-> hover with your mouse over the frame number box -> right click -> create a node osc handler

enable/disable -> use  'bpy.data.objects['Cube'].hide_viewport' and send a 1 or 0

**Comment by stephanebordonaro** [comment]
thx !

**Comment by stephanebordonaro** [comment]
![osc hide](https://user-images.githubusercontent.com/11030101/113322332-dbba9800-9314-11eb-9aed-6c2ac8eb298f.jpg)

**Comment by stephanebordonaro** [comment]
is it right?
thx

**Comment by stephanebordonaro** [comment]
![osc hide](https://user-images.githubusercontent.com/11030101/113322470-060c5580-9315-11eb-94c6-da30a9c9ea30.jpg)

**Comment by stephanebordonaro** [comment]
![Uploading osc hide2.JPG…]()

**Comment by stephanebordonaro** [comment]
![osc hide2](https://user-images.githubusercontent.com/11030101/113322839-7adf8f80-9315-11eb-817e-6948416c47bc.JPG)

**Comment by maybites** [comment]
that looks alright - but you don't need 'format' and 'loop' enabled to make it work (I think)

**Comment by stephanebordonaro** [comment]
argh ...doesn't work for me . maybe i miss something in : format , args or range ?

**Comment by maybites** [comment]
this works for me:

<pre><code>
----------begin_max5_patcher----------
372.3ocqSssaCBCC8Y3qHJZOxZ4Rus859LllpBfEMUPBJIzxTU+2WvAnsqcU
7vdIQ1w1myw14juGMU1BZJ4cxmDOuS9ddnqNGd81dzJVaVISigQMxhhRfF3d
R1XJAi46ZvUCJWXnju5eslYx1wEEaUPlwEPx5jYgAjkwcmwKFNGSgminHS2+
5xAPDMUbgEFj.Qi0Vwp.Cn1BBVZIhe3kDbDykQmyy99cGASTkUfVyJFkoAZQ
9SmaIlUK54ezjBy06jGIuD8mMiozIhBCwqD7JN9w8hjG1Kh+2zq.NZg4N41j
WqAQNIJd8LK+lEQdKLbTuOQTKV4D0lmIpnmNfuUTgWIJrVzRt32atHg57eqR
0xFU1vLoeyhbgQ4f1vELCWJtJlDWLOrWNUbRl.NQ2giSdr55CfR2GLBgcjsW
p5L2DflbgyD2CnJ3.eHd7m.koryGic3znPZQaWsf5RUlCJQCueewJNKj35fv
9qRWyb5.2Z7O6+SDglOr
-----------end_max5_patcher-----------
</code></pre>


address: /objects/Cube/show
datapath: bpy.data.objects['Cube'].hide_viewport
args[idx]: ()

**Comment by maybites** [comment]
![Uploading Screenshot 2021-04-01 at 19.16.31.png…]()

**Comment by maybites** [comment]
<img width="352" alt="Screenshot 2021-04-01 at 19 16 31" src="https://user-images.githubusercontent.com/148945/113330296-d9f5d200-931e-11eb-930c-09c8669fd17c.png">
