### ISSUE TITLE
How to send rotation OSC message as degree?

### ISSUE THREAD

**Issue by geddy75** [maybites/blender.NodeOSC#14]
Hello.
Thank you so much for your great work!

I have question about how to send object rotation OSC message as degree.
I attached screenshot.
<img width="787" alt="blender_osc" src="https://user-images.githubusercontent.com/29353551/127298496-96ec5d43-cbac-40b1-8599-5b931e96774d.png">

**Comment by maybites** [comment]
what is your question?

**Comment by maybites** [comment]
this should work..

datapath: bpy.data.objects['Cube'].rotation_euler[0]
arsg[idx]: ()
