### ISSUE TITLE
can install but cannot activate on Blender 3.0 Mac M1 mac

### ISSUE THREAD

**Issue by rocksolutions-io** [maybites/blender.NodeOSC#16]
Hello,
thanks for the wonderful plug in.
However, I am having problem with the plugin activation. 
I've managed to install the plugin, but when I click the plugin check box, error message show up as attached 
![Screenshot 2022-01-07 at 7 07 46 PM](https://user-images.githubusercontent.com/60421968/148535342-d54ed385-ae74-48e3-9c71-84d483926585.png)
Wondering how should I fix it? any pointers will be highly appreciated.
Thanks
RC

**Comment by maybites** [comment]
check out https://github.com/maybites/blender.NodeOSC/issues/5 and see if that helps..

**Comment by rocksolutions-io** [comment]
got it ... thanks for the reply

**Comment by cieeton** [comment]
Hi there, thanks for this great plug-in first. But I also have the same issue in Blender 3.1 on macOS 10.5.1. Here is the error text:
<img width="625" alt="Screenshot 2022-03-20 at 5 04 21 PM" src="https://user-images.githubusercontent.com/13039784/159155663-0f0cec80-e923-42dc-b8d5-f09e8f226691.png">
I installed the "blender.NodeOSC-2.3.1.zip" file, other versions doesn't work neither.  Not sure how to fix this, if there's any help would be grateful, thanks a lot!

**Comment by maybites** [comment]
please read the readme

**Comment by Yoshie026** [comment]
> Hi there, thanks for this great plug-in first. But I also have the same issue in Blender 3.1 on macOS 10.5.1. Here is the error text:
> <img alt="Screenshot 2022-03-20 at 5 04 21 PM" width="625" src="https://user-images.githubusercontent.com/13039784/159155663-0f0cec80-e923-42dc-b8d5-f09e8f226691.png">
> I installed the "blender.NodeOSC-2.3.1.zip" file, other versions doesn't work neither. Not sure how to fix this, if there's any help would be grateful, thanks a lot!

Hi, I'm having the same issue. Has this been resolved? Thank you!

**Comment by maybites** [comment]
https://github.com/maybites/blender.NodeOSC/releases

did you download from here?

**Comment by Yoshie026** [comment]
@maybites  Thank you for the response. Yes, I downloaded the zip file from the link and it still gives me the same error :(

**Comment by maybites** [comment]
can you check that the NodeOSC addon does not reside in a path where a folder has the term 'blender'  in any form in it?

**Comment by maybites** [comment]
this error usually occurs if people download the addon via 'Download zip' from the main page of this repo.

**Comment by Yoshie026** [comment]
I got rid of the help folder that contains max patch and blender file and tried but I get the same error.
