### ISSUE TITLE
blender 3.1 addon open failed

### ISSUE THREAD

**Issue by SHIELDXIE** [maybites/blender.NodeOSC#17]
Hi，Can you help me to find the problem, thank you very much!
![image](https://user-images.githubusercontent.com/37254173/161024328-72642df9-76da-49bb-838f-4ec9df45c9a3.png)
[system-info.txt](https://github.com/maybites/blender.NodeOSC/files/8388008/system-info.txt)

**Comment by maybites** [comment]
I will update the addon in the comming days.

in the meantime you could  try make the following change:

inside this file: 

https://github.com/maybites/blender.NodeOSC/blob/master/server/pythonosc/udp_client.py

change line 3 as stated here:

`from collections.abc import Iterable
`

that should do it. hopefully.

**Comment by SHIELDXIE** [comment]
It works, thanks so much!
