### ISSUE TITLE
NodeOSC 2.3.2 | Fix fails on MacOS M1 Max 

### ISSUE THREAD

**Issue by transvergence** [maybites/blender.NodeOSC#18]
Greetings.
NodeOSC is no longer working on recent versions of Blender on MacOS with Apple Silicon M1 chips. The ('from collections' to 'from collections.abc') fix that was proposed in earlier messages worked for a while, but no longer does. Can you please indicate what may need to be done to re-activate NodeOSC 2.3.2, or any version that can be made to work? Is it a Python issue? If so, what might need to be done there? Or is it a path issue? Is so, what is the recommended path where the add-on should reside? Any specific suggestions will be appreciated. Thank you. M

**Comment by maybites** [comment]
please adhere to the blenders [Best practices, tips and tricks for effective bug reporting.](https://wiki.blender.org/wiki/Process/Bug_Reports).
