### ISSUE TITLE
Problems receiving in windows

### ISSUE THREAD

**Issue by artrevinho** [maybites/blender.NodeOSC#2]
Im trying to setup an osc sender in localhost but im getting some troubles.
I format the message in the correct syntax as blender sends out, to control the energy of a light, 
but when i connect the server it receives the value just a moment and then when i change the value from the client , blender doesnt receive.

when is stop server running i recieve this message>

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\NodeOSC\server\_base.py", line 106, in modal
    return self.cancel(context)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\NodeOSC\server\_base.py", line 249, in cancel
    bpy.app.timers.unregister(execute_queued_OSC_callbacks)
ValueError: Error: function is not registered

location: <unknown location>:-1
 then when i try to connect again to same port doesnt allows me.
Thanks looking forward for a solution.

**Comment by maybites** [comment]
it looks as if there is more errors in the console. can you send me the complete stacktrace from the console? 

the restarting of the server is not working because there must have been an uncaught exception that made the server thread dereferenced but still running and thus blocking the port.

**Comment by artrevinho** [comment]
this is the full console . as i told it receives the message just a moment but not continues recieving

Server successfully started!
Server stopped!
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\NodeOSC\server\_base.py", line 106, in modal
    return self.cancel(context)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\NodeOSC\server\_base.py", line 249, in cancel
    bpy.app.timers.unregister(execute_queued_OSC_callbacks)
ValueError: Error: function is not registered

location: <unknown location>:-1

**Comment by maybites** [comment]
something looks really fishy. are you sure this is the latest release? (https://github.com/maybites/blender.NodeOSC/releases/download/V1.0.0/NodeOSC_V100.zip)

and for sure this is not the complete output from the console.

plus: please give me step by step instructions on how to reproduce.

**Comment by artrevinho** [comment]
Hello maybites, i will try to reproduce the situation, 
Open up blender, set up NodeOsc  and just the light energy parameter, then open vvvv to send OSC ,
Then when i send the osc bundle, it gets the value in blender and then freeze, afterward i disconnect the server and get the error i send to you.
I tried different OSC monitors to check that my data was correct sended and i even receive blender osc in VVVV .. but doesnt works at all, and the console give me that error.
Would be nice to know why this happens since i used a lot OSC in vvvv for several installations.
Thanks in advance

**Comment by maybites** [comment]
NodeOSC cannot handle OSC bundles as far as I can tell. only simple OSC messages. I don't know how to do this in vvvv, though. in MaxMSP its the [udpsend] object.

**Comment by artrevinho** [comment]
ok i will try to make a patch to send simply message and report, thanks

**Comment by artrevinho** [comment]
Actually i checked with your version of AddOSC and everything works fine, i gues node OSC doesnt read OSC in the right format , so the only way is to send direct messages via UDP,... Thats an issue cos if you wanna send lots of values bundles are the way, thanks

**Comment by maybites** [comment]
Actually I retract. If you use the python osc server it has basically the same implementation as addOSC. And I tested it with the [OpenSoundConrol] object, bundles are possible.

you have to give me reproducible steps for OSX...

**Comment by artrevinho** [comment]
maybe it regards to windows i think ,,,i can send you a patch of vvvv and try to run it remotely from a windows machine to an osx and check if it works. 
i tried to send bundle with VL a new visual programming tool in windows and get the same problem...
would be nice to fix it as NodeOsc seem much better that addOsc for my use. 
there is a nice osc monitor called Protokol. https://hexler.net/products/protokol
by the way i can read all messages from blender and vvvv.
and blender send it right too to vvvv and vl. 
If i can help you would be great.
Thanks mate

**Comment by maybites** [comment]
if you can post a link to a vvvv patch that causes the problems, that would be helpfull.

I will have a look at it next week.

**Comment by artrevinho** [comment]
Actually i tested your last release and works fine, so im happy you found the issue,, 
Now im trying to setup sorcar nodes,, how should i do it? thanks
