### ISSUE TITLE
BGE 3.0 publish issues 

### ISSUE THREAD

**Issue by jeff-song1122** [maybites/blender.NodeOSC#20]
BGE 3.0 publish issues 

![issue](https://user-images.githubusercontent.com/45113243/165939587-c8f64012-bd80-47cc-9c4c-fe8b51ea2e46.png)

**Comment by maybites** [comment]
please adhere to the blenders [Best practices, tips and tricks for effective bug reporting.](https://wiki.blender.org/wiki/Process/Bug_Reports).
