### ISSUE TITLE
GeoNodes parameters not supported?

### ISSUE THREAD

**Issue by baronlanteigne** [maybites/blender.NodeOSC#21]
This might not be a NodeOSC addon bug, I am not sure. But if it's not on your end, I figured you might want to know anyway.

When using the data path of a GN system parameter with NodeOSC, the parameter "update" won't be taken into consideration in the GN system.

Here's my data path as reference:

bpy.data.objects["3.instances"].modifiers["GeometryNodes"]["Input_2"]

A work around is to control a geo location with OSC, as a placeholder. The location can then drive the GN parameters.

**Comment by IASpaceAdmin** [comment]
can you provide a blend file and step by step instructions? I don't get it.

**Comment by baronlanteigne** [comment]
[GN_demo.zip](https://github.com/maybites/blender.NodeOSC/files/9293983/GN_demo.zip)

Try this demo blend file. The GN modifier input attribute is set to change the geo scale.
You can control this parameter via OSC, the parameter will move, but the GN system won't be updated.

If instead of control something else (like the position of an empty) and set up a parent relation, it should work.

**Comment by maybites** [comment]
this is a blender bug. (unless it is desired behavior, but I doubt it)

you can try the following:

open a python-console

copy-paste 

`bpy.data.objects["Cube"].modifiers["GeometryNodes"]["Input_3"] = 6.66`

enter

and you will see the value in the GUI is only updated once you hover the mouse over. but the node system is not updated at all.

**Comment by baronlanteigne** [comment]
Thanks. That makes sense!
