### ISSUE TITLE
Stopping the Service produces an error

### ISSUE THREAD

**Issue by Mangle101** [maybites/blender.NodeOSC#22]
Hi there 

the plugin starts off well, as soon as i stop the service i get a error

![nodeOSC_stopServiceError](https://user-images.githubusercontent.com/22413401/179407126-ca22d9e2-585c-4f20-9143-2a643ade0c60.png)

im using Blender 3.2

**Comment by maybites** [comment]
I can not confirm this error on my Mac system.

please provide me more info from the command line.
