### ISSUE TITLE
How to convert args?

### ISSUE THREAD

**Issue by PonieseValtyrk** [maybites/blender.NodeOSC#25]
My app on my Phone can only output XYZ rotation messages in three different addresses, however the rotaion information in Blender is a float array of 3 items. Can I convert these three addresses into one address with 3 args?

**Comment by PonieseValtyrk** [comment]
Solved, I recieved on Max and converted it to list then sent messages from max to blender.

**Comment by maybites** [comment]
you can do it in NodeOSC, too:

datapath: 
for x rotation: bpy.data.objects['Cube'].rotation_euler[0]
for y rotation: bpy.data.objects['Cube'].rotation_euler[1]
for z rotation: bpy.data.objects['Cube'].rotation_euler[2]
