### ISSUE TITLE
Cannot import/export OSC config with same address

### ISSUE THREAD

**Issue by arnaudjuracek** [maybites/blender.NodeOSC#26]
I see in your wiki that `it is possible and permissible to create multiple OSC handlers and nodes with the same OSC address`, but the way you structure your imported/exported config using JSON and address as object key neglect this.

```js
// Invalid json
{
  "/my-address": { …messageHandler1 }, 
  "/my-address": { …messageHandler2 }
}
```

Do you think you could format your config object as such :

```js
[
  { address: "/my-address", …messageHandler1 },
  { address: "/my-address", …messageHandler2 }
]
```

Or maybe I am missing something ?
Thank you for your time !

**Comment by maybites** [comment]
you are probably right. I never used that feature, its a leftover from an addon from which I started from, years ago.

**Comment by arnaudjuracek** [comment]
I made a pull request if you are interested.

FYI this import feature is used in one of my workflow to allow setting a lot of addresses programmatically by generating a JSON file using a script with another piece of software.
