### ISSUE TITLE
No module named Blender error when trying to enable the add-on

### ISSUE THREAD

**Issue by julscloudops** [maybites/blender.NodeOSC#29]
I receive a ModuleNotFoundError: No module named 'blender' when trying to enable the NodeOSC add-on. I just downloaded the zip and installed through the blender add-on page in Preferences.  Any clues into what I might be doing wrong or what troubleshooting might be required to fix this issue?

I'm on a Windows 11 64-bit computer running Blender 3.4.1

**Comment by maybites** [comment]
I assume you downloaded the repo. You can do that, but rename the addonfolder to "NodeOSC".

The dot in the folder name causes this error.

**Comment by julscloudops** [comment]
That was it! Thanks a lot :)
