### ISSUE TITLE
Node.OSC not working in Blender 4

### ISSUE THREAD

**Issue by jhoepffner** [maybites/blender.NodeOSC#31]
I just installed Blender 4
Spout is working but not OSC.
When I try to start Node.OSC, there is:
"Server startup: invalid syntax (<unknow>, line 0)"
Jacques

**Comment by maybites** [comment]
Hi
Can you post the complete log from the terminal?

**Comment by jhoepffner** [comment]
Hello,
In the Python console there is only:
OSCPy Server sended test message to 127.0.0.1 on port 9002
And the line:
"Server startup: invalid syntax (<unknown>, line 0)" (There is "unknown" between brackets before  ", line 0" not shown in the text)
in the bottom of Blender GUI
Nothing else…

**Comment by maybites** [comment]
are you using blender on osx?

**Comment by jhoepffner** [comment]
no, Windows 10
–––––––––––––––––––––––––––––––––––––––
Jacques Hoepffner
6, passage Dagorno
75020 Paris
cell +33 6 83 23 90 62
***@***.***
http://www.hoepffner.info

**Comment by maybites** [comment]
and there is no other output in the console window?

-> https://blender.stackexchange.com/questions/23147/how-do-i-get-the-console-on-windows

**Comment by jhoepffner** [comment]
no, only one line at each time I try to start the OSC server
–––––––––––––––––––––––––––––––––––––––
Jacques Hoepffner
6, passage Dagorno
75020 Paris
cell +33 6 83 23 90 62
***@***.***
http://www.hoepffner.info

**Comment by maybites** [comment]
are there message about the startup of the script?

**Comment by jhoepffner** [comment]
Presently teaching daVinci, not at home at the moment, will answer tonight (Paris time)…
–––––––––––––––––––––––––––––––––––––––
Jacques Hoepffner
6, passage Dagorno
75020 Paris
cell +33 6 83 23 90 62
***@***.***
http://www.hoepffner.info

**Comment by jhoepffner** [comment]
Hello,

Waiting the next day to start my computer, open Blender 4, start NodeOSC server and, Miracle!, it works!

Nothing changed…

Thank you for your distance influence.

Have a nice day,
Jacques
–––––––––––––––––––––––––––––––––––––––
Jacques Hoepffner
6, passage Dagorno
75020 Paris
cell +33 6 83 23 90 62
***@***.***
http://www.hoepffner.info

**Comment by maybites** [comment]
yeah, hmm. cheers?
