### ISSUE TITLE
Suggestion: send python commands as strings through OSC

### ISSUE THREAD

**Issue by baronlanteigne** [maybites/blender.NodeOSC#4]
A specific OSC address could interpret the received strings as python commands as they are shown in the Info Editor.

This would allow the mapping of some more global parameters (ie Render Engine) without having to map them twice (once in the software you control blender with and once more in NodeOSC.)

I'm not certain what the proper terminology is so I'll explain what I mean with an example that I would actually use today.

Sending: 
`/blender/script "bpy.context.space_data.lock_camera = True"`
Would enable Lock Camera to View in blender.

Thank you.

**Comment by maybites** [comment]
nice idea. certainly doable. maybe you could come up with a python script that does exactly this? (parsing the string and executes the script)
maybe find a solution that also can deal with other data that might be interesting (bool, int, float, vectors, lists etc.) . once I have that code I can implement it quite easily.

**Comment by baronlanteigne** [comment]
Thank you for your motivation. I think I can figure it out and I would love to contribute. I'll give it a try. I've never worked on an addon or even scripts in blender but i'll take a look at your scripts to get started.

**Comment by maybites** [comment]
I just realized that this feature is a very low hanging fruit with V2, So I implemented it and it is live with V2.0.2:

now you can send the following string:

`
/blender/script "bpy.data.scenes['Scene'].tool_settings.transform_pivot_point = 'CURSOR'"
`

and setting the handler thus

<img width="261" alt="Statementhandler" src="https://user-images.githubusercontent.com/148945/108278533-7606b800-717b-11eb-8060-04c39500a1be.png">

will execute your statement
