### ISSUE TITLE
Installation Issue 

### ISSUE THREAD

**Issue by babylon-detective** [maybites/blender.NodeOSC#5]
Tried to install, having an issue with clicking checkmark/turning it on, getting this error message. 
<img width="894" alt="Screen Shot 2020-03-13 at 23 30 04" src="https://user-images.githubusercontent.com/12578077/76674245-8b469000-6583-11ea-8158-4b449d97aa12.png">

[system-info.txt](https://github.com/maybites/blender.NodeOSC/files/4332253/system-info.txt)

**Comment by maybites** [comment]
Did you download the zip from https://github.com/maybites/blender.NodeOSC/releases ?

**Comment by babylon-detective** [comment]
Thank you, works now. 
trouble was with default master branch.

**Comment by Extrastout** [comment]
I am on blender 3.1 and dealing with the same issue of it installing, but not loading.
![Screen Shot 2022-03-14 at 5 06 18 PM](https://user-images.githubusercontent.com/4922990/158280762-73f32daa-571e-4b9e-aa42-2a8ee26c3503.png)
Tried multiple versions with varied errors, but this is with the latest posted from the link above. (releases April 2021)   
Any help would be greatly appreciated.  This is some powerful stuff on a Wacom Cintiq Pro with Touch.  Makes an amazing control surface once you use the Wacom touch APIs.

**Comment by maybites** [comment]
which file did you download?
