### ISSUE TITLE
Closing Blender doesn't properly "close" the OSC port

### ISSUE THREAD

**Issue by baronlanteigne** [maybites/blender.NodeOSC#6]
It happens when loading a different project too. The issue is that this port can no longer be used and a new one has to be selected. Stopping the process before closing solves the issue. Maybe closing projects (to open a new one) could force stop NodeOSC?

Also, I have it start when the project opens but I need to stop and restart NodeOSC for it to work but that's not a big deal.

**Comment by maybites** [comment]
1. fixed the loading project issue with c14882887e28becbf41fa12810b755190384999f
2. open project with autorun is expected behavior. please read the manual / tooltip.
