### ISSUE TITLE
QA: How to make it work with AN?

### ISSUE THREAD

**Issue by gerroon** [maybites/blender.NodeOSC#7]
Hi

I set this up and using an Android app to send messages and it seems to work since the values in the N panel changes but I cant get the AN node to receive anything. Please see the image below

https://i.imgur.com/JsCxOCU.png

**Comment by maybites** [comment]
1. stop  - start the osx server
2. make sure you have 'Auto Execution' on
3. make sure you have 'Property changed' toggled on.

**Comment by gerroon** [comment]
Hi 

Thanks for the reply, that is why I provided the image, it shows that all those options are enabled.

**Comment by maybites** [comment]
did you stop and restart the server?

**Comment by gerroon** [comment]
Yes many times, I cant make it work. I will keep trying I guess if that is the only way.

**Comment by gerroon** [comment]
Ok I got it working but it is  abit of weird. Everytime I add a new an node or change the setting in the AN node I need to restart the server. Is that the intended workflow? Is this a limitation with Blender?

**Comment by maybites** [comment]
this is the way NodeOSC is currently working. not ideal from a user perspective. but intended because of performance reasons. I am inclined to change this in the future but I need to check first if the performance penalty is really so severe as I imagined it when I settled for this behavior..

**Comment by gerroon** [comment]
It makes sense, I guess it is not such a big ordeal given that it seems to work once setup properly however it might be good to mention it in the wiki probably.

Thanks

**Comment by maybites** [comment]
With Version 2 the GUI has been improved an this missunderstanding cannot happen anymore.
